spring.application.name=erp-agence
# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/cubeit_erp
spring.data.mongodb.auto-index-creation=true

# Mailtrap (OTP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b4eae957e0db54
spring.mail.password=92dc871ceeb90c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
cubeit.app.jwtSecret=UneCleSecreteTresLonguePourSecuriserVosTokensCubeIT2026
cubeit.app.jwtExpirationMs=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html